cloud:
  aws:
    credentials:
      access-key: AKIAWVSSHJS2DFW4D25T
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: cafemanager.com

#
#spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2MB
#      max-file-size: 5MB
#      max-request-size: 10MB

server:
  port: 9090

